title: Shambhavi Nandini
description: |
  <p>Cloud Service Operations Assoc. Manager</p>
  <br>Address: Pune, 411046</br>
  Contact: +91 9741699318
  <br>Email: nandinishambhavi@gmail.com</br>
  <br>
  [LinkedIn](https://www.linkedin.com/in/shambhavi-nandini-70349474/) 
google_analytics:
theme: jekyll-theme-cayman
