title: Shambhavi Nandini
description: |
  <p>Cloud Service Operations Assoc. Manager</p>
  <br>Address: Pune, 411046</br>
  Contact: +91 9741699318
  <br>Email: nandinishambhavi@gmail.com</br>
google_analytics:
theme: jekyll-theme-cayman
